### ISSUE TITLE
Update client listing

### ISSUE THREAD

**Issue by tomusdrw** [JamBrains/jam-chain#10]
I would like to list/change the following JAM client implementation on https://jamcha.in/clients:

- Name: "typeberry"
- Bio: ""
- Optional website: "fluffylabs.dev"
- Language: "TypeScript"
- Language Set: "C"
- Finished milestones: 0
- Optional contact (email/matrix/tg etc): "@tomusdrw:matrix.org"

**Comment by ggwpez** [comment]
Here we go 🙌  https://jamcha.in/clients/12
