### ISSUE TITLE
Update client listing

### ISSUE THREAD

**Issue by prasad-kumkar** [JamBrains/jam-chain#11]
I would like to list/change the following JAM client implementation on https://jamcha.in/clients:

- Name: "Tessera"
- Bio: "A Team of Web3 Researchers+Devs; Currently private"
- Optional website: "chainscore.finance"
- Language: "Rust"
- Language Set: "B"
- Finished milestones: 0
- Optional contact (email/matrix/tg etc): "prasad@chainscore.finance"

**Comment by ggwpez** [comment]
Here we go https://jamcha.in/clients/13
