### ISSUE TITLE
Update client listing: Boka

### ISSUE THREAD

**Issue by xlc** [JamBrains/jam-chain#2]
I would like to list/change the following JAM client implementation on https://jamcha.in/clients:

- Name: Boka 
- Bio: TBD
- Optional website: ""
- Language: Swift
- Language Set: B
- Finished milestones: 0
- Optional contact (email/matrix/tg etc): bryan@acala.network

**Comment by ggwpez** [comment]
Added https://jamcha.in/clients/4 🙌   
Feel free to ping once here is a bio.

**Comment by xlc** [comment]
Let's use this one for now:
Boka / 波卡 / bō kǎ: JAM built with Swift. Developed by Laminar Labs.

**Comment by ggwpez** [comment]
Process moved to w3f https://github.com/w3f-webops/graypaper-website/issues/new?assignees=&labels=&projects=&template=client-listing-request.md&title=Client+Listing%3A+XYZ  
Will still update it here.
