### ISSUE TITLE
Update client listing

### ISSUE THREAD

**Issue by celadari** [JamBrains/jam-chain#5]
I would like to list/change the following JAM client implementation on https://jamcha.in/clients:

- Name: "Jam4s"
- Bio: "Scala  implementation of the JAM protocol. Currently not publicly visible."
- Optional website: "https://github.com/jam4scala/"
- Language: "Scala"
- Language Set: "D"
- Finished milestones: 0
- Optional contact (email/matrix/tg etc): "@sergei_astapov:matrix.org | @subotic:matrix.org | @celadari:matrix.org | @basedafdev:matrix.org"

**Comment by ggwpez** [comment]
Added https://jamcha.in/clients/7. Please re-open if something is wrong. Contact info will be displayed soon.
