### ISSUE TITLE
Update client listing

### ISSUE THREAD

**Issue by marcuspang** [JamBrains/jam-chain#6]
I would like to list/change the following JAM client implementation on https://jamcha.in/clients:

- Name: "marcuspang"
- Bio: "Working on Etheruem"
- Optional website: "https://marcuspang.me"
- Language: "Go"
- Language Set: "A: "Cooperate Code""
- Finished milestones: 0
- Optional contact (email/matrix/tg etc): "@marcuspang:matrix.org"

**Comment by ggwpez** [comment]
Should i use `marcuspang` as the name of the client software or do you have another name for it?

**Comment by marcuspang** [comment]
Hey @ggwpez, could you use `jamgo`? Thank you :)

**Comment by ggwpez** [comment]
Added https://jamcha.in/clients/8. LMK if you have a project description.

**Comment by ggwpez** [comment]
Process moved to w3f https://github.com/w3f-webops/graypaper-website/issues/new?assignees=&labels=&projects=&template=client-listing-request.md&title=Client+Listing%3A+XYZ
