### ISSUE TITLE
Update client listing - Zondax Jam

### ISSUE THREAD

**Issue by ainhoa-a** [JamBrains/jam-chain#7]
I would like to list/change the following JAM client implementation on https://jamcha.in/clients:

- Name: "Jelly"
- Bio: "Spread the Joy with Every Jar - Taste the Magic of Our Jam & Jelly!"
- Optional website: "[zondax.ch](http://zondax.ch/)"
- Language: "Julia"
- Language Set: "D:Correct Code"
- Finished milestones: 0
- Optional contact (email/matrix/tg etc): [jelly@zondax.ch](mailto:jelly@zondax.ch)

**Comment by ggwpez** [comment]
Added https://jamcha.in/clients/9. Please re-open if something is wrong. Contact info will be displayed soon.
