### ISSUE TITLE
Update client listing

### ISSUE THREAD

**Issue by philoniare** [JamBrains/jam-chain#8]
I would like to list/change the following JAM client implementation on https://jamcha.in/clients:

- Name: "JAM Forge"
- Bio: "We are a team of 8, experienced in Java and Kotlin blockchain development. "
- Optional website: ""
- Language: "Kotlin"
- Language Set: "A: Cooperate Code"
- Finished milestones: 0
- Optional contact (email/matrix/tg etc): "@philoniare:matrix.org"

**Comment by ggwpez** [comment]
Added https://jamcha.in/clients/10. Please re-open if something is wrong. Contact info will be displayed soon.
