### ISSUE TITLE
Colorful Notion/JAM DUNA

### ISSUE THREAD

**Issue by sourabhniyogi** [JamBrains/jam-chain#9]
I would like to list/change the following JAM client implementation on https://jamcha.in/clients:

- Name: "Colorful Notion/JAM DUNA"
- Bio: "Would love to connect our working QUIC implementation in Fall, organize a weeklong meetup at Devcon in Thailand"
- Optional website: "https://dune.com/substrate/jam-duna"
- Language: "Go"
- Language Set: "A"
- Finished milestones: 0
- Optional contact (email/matrix/tg etc): "https://t.me/colorfulnotion"

**Comment by ggwpez** [comment]
Added https://jamcha.in/clients/11 now. Contact info will be displayed soon.
